### ISSUE TITLE
Missing metrics for classification

### ISSUE THREAD

**Issue by BillyXYB** [enisimsar/latentswap3d#1]
For predict.py, it seems that the metics file contains classifier is missing. Could you include those or indicate their origin?
Thank you.

**Comment by enisimsar** [comment]
Hello,

I appreciate your interest.

You can download the `metrics` folder via [this link](https://drive.google.com/drive/folders/1MvYdWCBuMfnoYGptRH-AgKLbPTsIQLhl).

Please let me know for any other questions.
