### ISSUE TITLE
environment

### ISSUE THREAD

**Issue by luchaoqi** [enisimsar/latentswap3d#2]
Hello,

I was following the example here: https://github.com/enisimsar/latentswap3d#example-for-mvcgan and  wondering how to run editing under eg3d's setting. I was trying to run the code `python predict.py hparams.batch_size=50 load_path=$OUTPUT_PATH generator=eg3d generator.class_name=ffhq` but the classifier requires tensorflow back to `1.xxx` versions whereas in `env.yml` the tensorflow is `2.xxx` version?

error msg:
```
  File "/xxx/latentswap3d/src/classifiers/stylegan2/dnnlib/tflib/tfutil.py", line 16, in <module>
    import tensorflow.contrib   # requires TensorFlow 1.x!
ModuleNotFoundError: No module named 'tensorflow.contrib'
```

**Comment by enisimsar** [comment]
Hello,

Thank you for your interest in our work. 

To run the StyleGAN2 classifiers, you need to install version `1.15.4-gpu` 

https://github.com/enisimsar/latentswap3d/blob/0bd30cde15d36fe7381cb65adc448729859cc2b4/env.yml#L274 

Please let me know if you have any questions.
